# Main Colors
unrecognized_file: lightgray
recognized_file:   white
dir:               blue

# Link
dead_link: red
link:      magenta

# Access Modes
write:     yellow
read:      gray
exec:      red
no_access: dimgray

# Age
day_old:     lightblue
hour_old:    white
no_modifier: lightgray

# File Size
file_large:  white
file_medium: lightgray
file_small:  darkgray

# Random
report: white
user:   cyan
tree:   dimgray
empty:  yellow
error:  red
normal: darkgray

# Git
addition:     green
modification: yellow
deletion:     red
untracked:    darkgray
unchanged:    white
